---
  - name: create a directory
    file:
      path: /srv/nfs
      state: directory
      owner: vagrant
      group: vagrant
      mode: 777
    when: inventory_hostname == "node2"
    register: directory
  - debug: 
      var: directory
    when: directory.changed
