---
- name: install nfs server
  yum:
    name: nfs-utils
    state: present
  register: install_nfs
  when: '"node2" in inventory_hostname'    

- name: start firewalld 
  service:
    name: firewalld
    state: started
    enabled: yes
  when: inventory_hostname == "node2"

- name: allow firewall rules
  firewalld:
    port:
      - 22/tcp
      - 111/tcp
      - 111/udp
      - 2049/tcp
      - 20048/tcp
      - 20048/udp
      - 39096/udp
      - 39423/tcp
      - 52917/udp
    permanent: yes
    immediate: yes
    state: enabled
  register: firewalld
  ignore_errors: yes
  when: '"node2" in inventory_hostname'    
    
- name: start nfs service
  service:
    name: nfs-server
    state: started
    enabled: yes
  register: nfs_server
  when: '"node2" in inventory_hostname'
- debug:
    var: install_nfs
- debug:
    var: firewalld
- debug:
    var: nfs_server
