- name: create file
  file:
    path: "/tmp/{{ item }}"
    state: touch
  loop:
    - alpha
    - beta
    - cuda
    - delta
    - fifa
    - gamma
  register: file1
  when: inventory_hostname == "node3" or inventory_hostname == "node4" or inventory_hostname == "node1"
    
#- name: debug
#  debug:
#    var: file1
