---
  - name: remove file
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /tmp/alpha
      - /tmp/beta
      - /tmp/cuda
      - /tmp/delta
      - /tmp/fifa
      - /tmp/gamma
