---
- name: mounting
  mount:
    name: /nfs
    src: {{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }}:/srv/nfs
    fstype: nfs4
    opts: defaults
    state: mounted
  register: mounting
- debug:
    var: mounting