---
  - name: Create a user,Directory and other tasks
    hosts: all
    become: true
    tasks:
      - name: create user
        user:
          name: nfsuser
          state: present
          groups: wheel
        when: '"node2" in inventory_hostname'  

      - name: create a directory 
        file:
          path: /srv/nfs
          state: directory
          owner: nfsuser
          mode: 777
        when: '"node2" in invetory_hostname'  
      


      - name: remove file
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - /tmp/alpha
          - /tmp/beta
          - /tmp/cuda
          - /tmp/delta
          - /tmp/fifa
          - /tmp/gamma
